### ISSUE TITLE
Conflicting shortcuts with other bundles

### ISSUE THREAD

**Issue by d2s** [liamr/Zurb-Foundation-Textmate-Bundle#1]
Interesting project. Before I started to install, tested if there were already some conflicting character combinations on on Sublime Text 2. Noticed at least one possible problem when [Sublime 2 ZenCoding](https://bitbucket.org/sublimator/sublime-2-zencoding/src) extension is installed.
## btn

Conficts with [ZenCoding](http://code.google.com/p/zen-coding/wiki/ZenHTMLElementsEn) shortcut:

```
<button></button>
```
## fr

Another possible conflict but not sure where ST2 is picking this from (probably not from ZenCoding).
Should look more closely later.

```
<frame></frame>
```

**Comment by liamr** [comment]
Hey! Cheers for that! Might change it to zfr & zfbtn? What you think, I'd say that might cut down on conflicts?

**Comment by d2s** [comment]
That could be the answer. At least I don't know if there are any similar shortcuts (at least not on my setup).

**Comment by liamr** [comment]
Updated the Bundle so all snippets are prepended with 'zf' - that should take care of things! Cheers for bring that up.
